# Generated by Django 4.0 on 2022-04-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0013_alter_residents_user'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechargepayments',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='residents.residents', to_field='resident_code'),
        ),
        migrations.AlterField(
            model_name='transformerlevypayments',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='residents.residents', to_field='resident_code'),
        ),
    ]
