# Generated by Django 4.0 on 2022-06-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_servicechargepayments_resident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechargepayments',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Payment Verified'), (0, 'Verification Pending'), (2, 'Payment Not Valid')], default=0, verbose_name='payment_status'),
        ),
        migrations.AlterField(
            model_name='transformerlevypayments',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Payment Verified'), (0, 'Verification Pending'), (2, 'Payment Not Valid')], default=0, verbose_name='payment_status'),
        ),
    ]
